camera_type: PhoXiCamera
camera_name: a_phoxi_m_camera
robot_name: b_bot
eye_on_hand: false
robot_base_frame: workspace_center
robot_effector_frame: b_bot_flange
robot_effector_tip_frame: b_bot_gripper_tip_link
camera_parent_frame: workspace_center
marker_map: marker-26-70
enclosed_marker: false
detection_mode: 0
planarity_tolerance: 0.001
initpose: [0.10,  0.10, 0.35, -180, 90, 0]
keyposes:
  - [0.17,  0.15, 0.16, -150, 25, 0]
  - [0.17,  0.00, 0.16, -150, 25, 0]
  - [0.17, -0.10, 0.16, -150, 25, 0]

# - [0.17, -0.05, 0.25, -150, 25, 0]
# - [0.17,  0.05, 0.25, -150, 25, 0]
# - [0.17,  0.20, 0.25, -150, 25, 0]

# - [0.40,  0.20, 0.15, -150, 25, 0]
# - [0.40,  0.05, 0.15, -150, 25, 0]
# - [0.40, -0.10, 0.15, -150, 25, 0]

  - [-0.05, -0.15, 0.16, -150, 25, 0]
  - [-0.05,  0.00, 0.16, -150, 25, 0]
  - [-0.05,  0.15, 0.16, -150, 25, 0]
