camera_type: DepthCamera
camera_name: realsense
robot_name: arm
eye_on_hand: true
robot_base_frame: basement_link
robot_effector_frame: arm_ee_link
robot_effector_tip_frame: magnet_tip_link
camera_parent_frame: magripper_realsense_flange
marker_map: markermap-17_26_32_256
marker_size: 0.070
detection_mode: 1
planarity_tolerance: 0.003
initpose: [0.40, 0.05, 0.60, 90, 0, 0]
keyposes:
  - [ 0.10,  0.05, 0.50,  90, -25,   0]
  - [ 0.15,  0.05, 0.55,  90, -15,   0]
  - [ 0.35,  0.05, 0.55,  90,   0,   0]
  - [ 0.45,  0.05, 0.55,  90,  15,   0]
  - [ 0.55,  0.05, 0.55,  90,  25,   0]
  - [ 0.30, -0.25, 0.55, 115,   0,   0]
  - [ 0.30, -0.10, 0.55, 105,   0,   0]
  - [ 0.30,  0.20, 0.55,  75,   0,   0]
  - [ 0.30,  0.35, 0.55,  55,   0,   0]
speed: 0.1
