robots:
  d_bot:
    default_gripper: d_bot_gripper

grippers:
  d_bot_gripper:
    type:          RobotiqGripper
    controller_ns: d_bot_gripper_controller
    max_effort:    5.0
    velocity:      0.1

cameras:
  d_bot_camera: RealSenseCamera
  d_phoxi_m_camera: PhoXiCamera
