marker_map:           marker-26-70
enclosed_marker:      false
detection_mode:       0
marker_frame:         b_bot_ar_marker
reference_frame:      workspace_center
camera_parent_frame:  workspace_center
robot_name:           b_bot
robot_effector_frame: b_bot_flange
initpose:             [0.10,  0.10, 0.35, -180, 90, 0]
keyposes:
  - [0.17,  0.20, 0.16, -180, 25, 0]
  - [0.17,  0.10, 0.24, -180, 25, 0]
  - [0.17,  0.00, 0.32, -180, 25, 0]
  - [0.17, -0.10, 0.24, -180, 25, 0]
  - [0.17, -0.20, 0.16, -180, 25, 0]

  - [0.05, -0.15, 0.32, -180, 25, 0]
  - [0.05, -0.07, 0.24, -180, 25, 0]
  - [0.05,  0.00, 0.16, -180, 25, 0]
  - [0.05,  0.10, 0.21, -180, 25, 0]
  - [0.05,  0.20, 0.26, -180, 25, 0]
